services:
  - type: web
    name: telegram-image-blur-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8285636468:AAFPRQ1oS1N3I4MBI85RFEOZXW4pwBrWHLg
